### ISSUE TITLE
Year prompt is breaking this generator

### ISSUE THREAD

**Issue by SBoudrias** [jozefizso/generator-license#10]
I made a note on the relevant commit, but these lines are breaking this generator: https://github.com/jozefizso/generator-license/blob/master/app/index.js#L69-L72

That is not a valid Inquirer prompt.

Either way, I think we're better not making a prompt out of this. It is verbose and probably no one needs to manually define the year. If you really want one, then create an option as it won't clutter the interface.

**Comment by jozefizso** [comment]
Ou, I created a really f***ed uped release.

The year option is there to allow it to set from unit tests. I did not anticipate the user would enter it, although in rare cases it is possible they want to set a different year. It is really not necessary to ask everybody about the year.

When I was testing it from command line, it worked fine and did not crash, but I see now that my published version crashes.
