### ISSUE TITLE
Consider removing dev dependencies before publishing a package.

### ISSUE THREAD

**Issue by springcomp** [jozefizso/generator-license#124]
Please, consider removing dev dependencies when publishing a package.
This will help reduce the vulnerabilities reported when installing a package to only those that can actually have an impact on our users.

**Comment by jozefizso** [comment]
Installing the `generator-license` package will install only the application runtime code and the templates. No development dependencies are installed.

<img width="216" alt="Screenshot 2023-09-25 at 11 00 05" src="https://github.com/jozefizso/generator-license/assets/287778/7e9d3f56-cdde-4877-bf71-192f852a3f60">

**Comment by springcomp** [comment]
I read that this was indeed the case but was never able to actually make it work.
Here is my repro case:

```bash
mkdir p
cd p/
npm init --yes
npm install yeoman-generator@5
```

> added 318 packages, and audited 319 packages in 9s
>
>40 packages are looking for funding
>  run `npm fund` for details

found 0 vulnerabilities

```bash
npm install generator-license
```

> added 582 packages, and audited 901 packages in 20s
> 
> 75 packages are looking for funding
>   run `npm fund` for details
> 
> 11 vulnerabilities (3 moderate, 3 high, 5 critical)
> 
> To address all issues, run:
>   npm audit fix
> 
> Run `npm audit` for details.
> 


This does not happen after applying my suggested PR.
Can you point me what I’m doing wrong ?

**Comment by jozefizso** [comment]
This is standard behaviour of npm. Use the `--production` flag when installing to exclude the dev dependencies.

**Comment by springcomp** [comment]
> This is standard behaviour of npm. Use the `--production` flag when installing to exclude the dev dependencies.

This also happens, unfortunately, when using `--production` or `--omit=dev` flags.

**Comment by jozefizso** [comment]
I think the correct way is to update the vulnerable dependencies and not to hide the fact that particular package was built or is using old packages.

**Comment by jozefizso** [comment]
Please try v5.6.0 package.

**Comment by springcomp** [comment]
> Please try v5.6.0 package.

Thank you that works.
