### ISSUE TITLE
composeWith instruction

### ISSUE THREAD

**Issue by iamstarkov** [jozefizso/generator-license#21]
I tried to use your generator with mine using `composeWith` and a bit hard. Can you add small instruction how to use it with other generators?

**Comment by jozefizso** [comment]
This is how `generator-node` uses this library to create a license file with `composeWith` API:

https://github.com/yeoman/generator-node/blob/f003edac31a96e14ff7dba461fdfda753cc41252/generators/app/index.js#L305-L315
