### ISSUE TITLE
Additional LICENSEs

### ISSUE THREAD

**Issue by ek9** [jozefizso/generator-license#45]
I decided to open an issue to discuss addition of a few more licenses:

- `LGPL 3.0` GNU Lesser General Public License - allows use and distribution of modified software without revealing the source code. Useful permissive license for some libraries.
- `Eclipse Public License 1.0` - an Open Source Initiative approve license, derived from CPL (Common Public License). Endorsed and used by Eclipse Foundation.

1. I can issue issue a PR for `LGPL 3.0`.With `LGPL 3.0` would then have all the licenses from choosealicense.com

2. I can issue a PR for ( `Eclipse Public License 1.0` if you think it would be worth including it.

This would make most popular and **open-source initiative approved / OSD compliante** licenses available in the generator.

Feel free to use this to discuss what licenses can be added.
Looking forward to comments.

p.s. I just published my Creative Commons LICENSE generator which was inspired by this one. Feel free to check it if you are using Creative Commons LICENSES (they are good to license documentation or written material, but not for actual code): https://github.com/ek9/generator-license-cc

**Comment by SBoudrias** [comment]
What would you think of making the license generator smarter and ask questions to get a reduced set of relevant license?

```
? What type of project are you creating
- Library/Package
- Documentation
- Art
- Internal project

? What restriction do you want to apply
- No restriction (free)
- Acknowledge author
- Private

[And here we display a list of relevant licenses]
```

**Comment by ek9** [comment]
It depends what kind of licenses you want to keep here. I think what you suggest could be part of separate generator (i.e. `generator-license-wizard`), which could use this generator as a sub-generator. I am not sure how authors of this see this package, but I see it as a quick list of very commonly used licenses for software projects. Sometimes OSS projects choose to license code under licenses as such, but then choose to license documentation under CreativeCommons licenses.

Also, there is already a package for what you are suggesting: https://www.npmjs.com/package/generator-simple-license/tutorial It's a bit basic, it would make more sense to update that one and keep this one to serve a simpler task of just LICENSE file generation for certain licenses.

**Comment by ek9** [comment]
I've submited a PR for LGPL 3.0. Otherwise I think we can close this after LGPL is accepted as there is little point to have EPL in. If someone would really liks to use it, and ends up using this generator, they can always submit a PR. Suggesting to close once #61 is merged.
