### ISSUE TITLE
Coveralls.io integration for test coverage tracking

### ISSUE THREAD

**Issue by ek9** [jozefizso/generator-license#55]
I suggest to add coveralls.io integration for the project. This would allow us to track code coverage and see which tests are remaining to write. This information would also be displayed in the PRs.

Let me know what you think, I can submit a PR for this.

**Comment by SBoudrias** [comment]
I think a PR would be good. But let's keep the setup simple.

I'd:

- Use `jest` as test runner to get automatic coverage we can send to coveralls without any extra plugins and setup.
- `eslint` for enforcing linting and code style rules

**Comment by ek9** [comment]
Initial PR with Gulp \ Istanbul as jest setup did not look as easy to me, while I had already done setup on similar package with Gulp so I ported this.

Have a look at #56 PR and merge it. If this goes in I will do Eslint via separate PR for #54  issue

**Comment by ek9** [comment]
p.s. You can see in the test results that the project currently has 100% test coverage, which is great.
