### ISSUE TITLE
Adding good compasability support

### ISSUE THREAD

**Issue by SBoudrias** [jozefizso/generator-license#6]
Hey, would you merge a major pull request rehauling this generator to allow easy composability?

We're completely redoing the official `generator-node`, and we'd love to compose with this generator. But the code in here is pretty old and will not play super well with our.

**Comment by jozefizso** [comment]
This sounds great. I would appreciate rewrite that allows easier integration with other tools.

**Comment by jozefizso** [comment]
Implemented in https://github.com/jozefizso/generator-license/pull/7
