### ISSUE TITLE
Fill in package.json license field

### ISSUE THREAD

**Issue by SBoudrias** [jozefizso/generator-license#8]
It'd be nice to have this generator fill the [license field in package.json](https://docs.npmjs.com/files/package.json#license).

From npm documentation:

> The simplest way, assuming you're using a common license such as BSD-3-Clause or MIT, is to just specify the standard SPDX ID of the license you're using

Here are the ID https://spdx.org/licenses/

**Comment by sindresorhus** [comment]
You can get the license IDs from https://github.com/sindresorhus/spdx-license-list to validate.

**Comment by jozefizso** [comment]
Implemented in https://github.com/jozefizso/generator-license/pull/7
