### ISSUE TITLE
Add Support For No Email & Website

### ISSUE THREAD

**Issue by ghost** [jozefizso/generator-license#81]
The Generator Just Converts false, null etc. to a string.

I am composing it in my own generator

**Comment by millette** [comment]
I had a similar problem, which I tried to address with #84 but I am revisiting today. Patch to follow...

**Comment by millette** [comment]
After spending a bit more time then I would have wanted, I'm stuck with the various default values fields may take. Either from store: true, git-config, etc. I still haven't found a clean way to make fields (and prompts) optionnal or writing tests for it. I'm going to set this aside, hopefully someone more knowledgeable will be able to tackle this.

**Comment by SBoudrias** [comment]
Fixed, thanks @millette
