### ISSUE TITLE
Deleting license field when value is UNLICENSED seems to be incorrect

### ISSUE THREAD

**Issue by jramos-br** [jozefizso/generator-license#89]
According to https://docs.npmjs.com/files/package.json#license:

> Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:
> { "license": "UNLICENSED" }
> Consider also setting "private": true to prevent accidental publication.

Sorry if I miss something, but seem to me that license field must exist and, if desired, to prevent accidental publication, private field should by set to true.

**Comment by jozefizso** [comment]
Seems legit. I think it's a side effect from the https://github.com/jozefizso/generator-license/pull/83 as **UNLICENSED** was **nolicense** before and it was intended it will remove the license field.
